name: inject_generator
version: 1.0.0-alpha
description: Dev-time dependency for package:inject.
authors:
  - Matan Lurey <matanl@google.com>
  - Yegor Jbanov <yjbanov@google.com>
homepage: https://pub.dartlang.org/packages/inject

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: ^0.38.5
  build: ^1.2.0
  code_builder: ^3.2.0
  collection: ^1.14.11
  dart_style: ^1.3.1
  logging: ^0.11.3+2
  meta: ^1.1.7
  path: ^1.6.4
  quiver: ^2.0.5
  stack_trace: ^1.9.3

dev_dependencies:
  build_runner: ^1.7.1
  build_test: ^0.10.9+1
  inject:
    path: ../inject
  test: ^1.9.1
