name: inject.example.coffee
description: A simple example of using package:inject

dependencies:
  inject:
    path: ../../package/inject

dev_dependencies:
  build_runner: ^1.7.1
  build_test: ^0.10.9+1
  build_web_compilers: ^2.7.1
  inject_generator:
    path: ../../package/inject_generator
  test: ^1.9.1
